"""
    model settings
"""

norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoderCon',
    pretrained=None,
    with_seg=True,
    with_cdt=True,
    with_aux_cdt=True,
    with_ensemble=(False, 'add'),
    ensemble_weight=(0.4, 0.3, 0.3),
    backbone=dict(
        type='DCtlNet',
        class_of_model='LinkNet3DIter',
        temporal_kernel=3 + 0,
        num_iters=2,
        in_channels=1,
        base_channels=32,
        num_stages=4,
        strides=(1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2),
        dec_num_convs=(2, 2, 2),
        downsamples=(True, True, True),
        enc_dilations=(1, 1, 1, 1),
        dec_dilations=(1, 1, 1),
        with_cp=False,
        conv_cfg=[{'type': 'Conv3d'}, None],
        norm_cfg=[dict(type='BN3d', requires_grad=True),
                  dict(type='BN', requires_grad=True)],
        act_cfg=dict(type='ReLU'),
        upsample_cfg=dict(type='InterpConv'),
        norm_eval=False),
    decode_head=dict(
        decode_head_seg=dict(
            type='ConHead',
            head_flag='seg',
            freeze=False,
            in_channels=32,
            in_index=0,
            channels=32,
            num_convs=1,
            concat_input=False,
            dropout_ratio=0.1,
            num_classes=2,
            out_channels=2,
            threshold=0.40,
            norm_cfg=norm_cfg,
            align_corners=False,
            loss_decode=[
                dict(type='CrossEntropyLoss', loss_weight=1.0),
                dict(type='DiceLoss', loss_weight=4.0),
            ]),
        decode_head_cdt=dict(
            type='ConHead',
            head_flag='cdt',
            freeze=True,
            in_channels=32,
            in_index=0,
            channels=32,
            num_convs=1,
            concat_input=False,
            dropout_ratio=0.1,
            num_classes=1,
            out_channels=1,
            threshold=0.30,
            norm_cfg=norm_cfg,
            align_corners=False,
            loss_decode=[
                dict(type='MSELoss', loss_weight=1.0),
            ]),
    ),
    auxiliary_head=[
        dict(
            decode_head_seg=dict(
                type='ConHead',
                head_flag='seg',
                freeze=False,
                in_channels=32,
                in_index=1,
                channels=32,
                num_convs=1,
                concat_input=False,
                dropout_ratio=0.1,
                num_classes=2,
                out_channels=2,
                threshold=0.40,
                norm_cfg=norm_cfg,
                align_corners=False,
                loss_decode=[
                    dict(type='CrossEntropyLoss', loss_weight=1.0),
                    dict(type='DiceLoss', loss_weight=4.0),
                ]),
            decode_head_cdt=dict(
                type='ConHead',
                head_flag='cdt',
                freeze=True,
                in_channels=32,
                in_index=1,
                channels=32,
                num_convs=1,
                concat_input=False,
                dropout_ratio=0.1,
                num_classes=1,
                out_channels=1,
                threshold=0.30,
                norm_cfg=norm_cfg,
                align_corners=False,
                loss_decode=[
                    dict(type='MSELoss', loss_weight=1.0),
                ]),
        ),
        dict(
            decode_head_seg=dict(
                type='ConHead',
                head_flag='seg',
                freeze=False,
                in_channels=32,
                in_index=2,
                channels=32,
                num_convs=1,
                concat_input=False,
                dropout_ratio=0.1,
                num_classes=2,
                out_channels=2,
                threshold=0.40,
                norm_cfg=norm_cfg,
                align_corners=False,
                loss_decode=[
                    dict(type='CrossEntropyLoss', loss_weight=1.0),
                    dict(type='DiceLoss', loss_weight=4.0),
                ]),
            decode_head_cdt=dict(
                type='ConHead',
                head_flag='cdt',
                freeze=True,
                in_channels=32,
                in_index=2,
                channels=32,
                num_convs=1,
                concat_input=False,
                dropout_ratio=0.1,
                num_classes=1,
                out_channels=1,
                threshold=0.30,
                norm_cfg=norm_cfg,
                align_corners=False,
                loss_decode=[
                    dict(type='MSELoss', loss_weight=1.0),
                ]),
        ),
    ],

    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
